### ISSUE TITLE
关于tag pose维度问题

### ISSUE THREAD

**Issue by Mingchi-Yeh** [nooploop-dev/nlink_parser#3]
我使用的是具有IMU的UWB,并在环境中设置了4个anchor及1个tag
在订阅了 /nlt_nodeframe1_pose_node0 后,发现姿态好像只有x y z三个自由度,并没有四元数的旋转
想请问一下若仅使用具有IMU的UWB是否可估测旋转呢？或是说UWB的pose是只支援三个自由度的pose？

**Comment by nooploop-dev** [comment]
提供的是已经解算好的姿态角
